baseURL = 'https://robin-castellani.github.io'
defaultContentLanguage = "en"
languageCode = 'en-us'

title = 'Metamorphosis'

theme = "gokarna"

# disable automatic crawling
enableRobotsTXT = false

[params]
  # URL for the avatar on homepage
  avatarURL = "https://github.com/Robin-Castellani/robin-castellani.github.io/blob/main/static/images/me.jpg?raw=true"
  avatarAltText = "Wall Italian Lizard"
  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = "size-l"

  # Description to display on homepage
  description = "... fatti non foste a viver come bruti, ma per seguir virtute e canoscenza."

  # Accent color is displayed when you hover over <a> tags
  accentColor = "#009e22"

  # Display "back to top" button on posts
  ShowBackToTopButton = true

  # Footer text
  footer = "Robin Castellani"

  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/robin-castellani/"},
    {name = "github", url = "https://www.github.com/robin-castellani/"},
  ]


[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "posts"

    url = "/posts/"
    
    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"
    
    pre = "<span data-feather='book'></span>"

    # Weights are used to determine the ordering
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/robin-castellani"
    weight = 3   
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"
    
  [[menu.main]]    
    identifier = "linkedin"
    url = "https://linkedin.com/in/robin-castellani/"
    weight = 3
    
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='linkedin'></span>"
    
  [menu.main.params]
    newPage = true
